image: "scorpil/rust:stable"

before_script:
  - apt-get update -qq && apt-get install -y -qq libssl-dev pkg-config libopus-dev libsodium-dev
  - cargo --version
  - rustc --version

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: cargo test

deploy_vps:
  stage: deploy
  script:
    - echo "No deploy set up yet"
  environment:
    name: taha vps
  only:
  - master



build:
  stage: build
  script:
    - cargo build --release
  cache:
    paths:
      - target/
  artifacts:
    paths:
      - target/release/discord-markov-bot


