image: "scorpil/rust:stable"

before_script:
  - apt-get update -qq && apt-get install -y -qq libssl-dev pkg-config
  - cargo --version
  - rustc --version


stages:
  - build

build:
  stage: build
  script:
    - cargo build --release
  cache:
    paths:
      - target/
  artifacts:
    paths:
      - target/release/discord-markov-bot

