stages:
  - build
#  - test
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

build:
  image: "jimmycuadra/rust"
  before_script:
    - apt-get update -qq && apt-get install -y -qq libssl-dev pkg-config libsqlite3-dev
    - cargo --version
    - rustc --version
  stage: build
  script:
    - cargo build --release
  cache:
    untracked: true
    paths:
      - target/
      - cargo/
  artifacts:
    paths:
      - target/release/discord-markov-bot

#test:
#  image: "scorpil/rust:stable"
#  before_script:
#    - apt-get update -qq && apt-get install -y -qq libssl-dev pkg-config libsodium-dev libsqlite3-dev
#    - cargo --version
#    - rustc --version
#  stage: test
#  cache:
#    untracked: true
#    paths:
#      - target/
#      - cargo/
#  script: cargo test --release
#
deploy_vps:
  image: "governmentpaas/curl-ssl"
  stage: deploy
  script:
    - curl --version
    - curl https://tahahawa.me/deploy_markov_bot -f -m 300 -# -S
  environment:
    name: taha vps
  only:
  - master
