[package]
name = "discord-markov-bot"
version = "0.2.2"
authors = ["Taha Hawa <tahahawa@gmail.com>"]

[dependencies]
serde = "0.9"
serde_yaml = "0.6"
r2d2 = "0.7"
r2d2_sqlite = "0.2"
rusqlite = "0.11"
markov = "0.0.32"
typemap = "0.3.3"
regex = "0.2"

[dependencies.serenity]
git = "https://github.com/zeyla/serenity.git"
default-features = false
features = ["cache", "framework", "extras"]
