[package]
name = "discord-markov-bot"
version = "0.2.3"
authors = ["Taha Hawa <tahahawa@gmail.com>"]

[dependencies]
serde = "1.0"
serde_yaml = "0.7"
r2d2 = "0.7"
r2d2_sqlite = "0.2"
rusqlite = "0.12"
markov = "0.0.32"
typemap = "0.3.3"
regex = "0.2"

[dependencies.serenity]
git = "https://github.com/zeyla/serenity.git"
default-features = false
features = ["cache", "builtin_framework", "builder", "client", "utils", "model"]
