[package]
name = "discord-markov-bot"
version = "0.1.0"
authors = ["Taha Hawa <tahahawa@gmail.com>"]

[dependencies]
serde = "0.9.10"
serde_yaml = "0.6.2"
r2d2 = "0.7.1"
r2d2_sqlite = "0.1.2"
rusqlite = "0.9"
markov = "0.0.32"
typemap = "0.3.3"

[dependencies.serenity]
git = "https://github.com/zeyla/serenity.git"
default-features = false
features = ["cache", "framework"]


