[package]
name = "discord-markov-bot"
version = "0.1.0"
authors = ["Taha Hawa <tahahawa@gmail.com>"]

[dependencies]
serde = "0.8"
serde_yaml = "0.5"

[dependencies.serenity]
git = "https://github.com/zeyla/serenity.git"
default-features = false
features = ["cache", "framework"]


