[package]
name = "discord-markov-bot"
version = "0.5.0"
authors = ["Taha Hawa <tahahawa@gmail.com>"]

[dependencies]
serde = "1.0"
serde_yaml = "0.7"
markov = "1.0"
typemap = "0.3"
regex = "1.0"
diesel = {version = "1.3",features = ["postgres","r2d2", "numeric", "bigdecimal", "chrono"]}
num = "0.2.0"
bigdecimal = "0.0.14"
chrono = "0.4.5"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity.git"
# git = "https://github.com/tahahawa/serenity.git"
#branch = "feature/tungstenite-switch"
default-features = false
features = ["cache", "framework", "builder", "client", "utils", "model", "standard_framework"]
