[package]
name = "discord-markov-bot"
version = "0.4.0"
authors = ["Taha Hawa <tahahawa@gmail.com>"]

[dependencies]
serde = "1.0"
serde_yaml = "0.7"
markov = "0.0.33"
typemap = "0.3.3"
regex = "0.2"
diesel = { version = "1.1.0", features = ["sqlite","r2d2"] }

[dependencies.serenity]
git = "https://github.com/zeyla/serenity.git"
# git = "https://github.com/tahahawa/serenity.git"
#branch = "v0.5.0"
default-features = false
features = ["cache", "framework", "builder", "client", "utils", "model", "standard_framework"]
